name: Production Branch Protection

on:
  pull_request:
    branches:
      - production

jobs:
  restrict-to-release-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge branch
        if: github.event.pull_request.base.ref == 'production'
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "release" ]; then
            echo "Merges to main are only allowed from the release/QA branch."
            exit 1
          fi 
