name: Branch Protection Release

on:
  pull_request:
    branches: 
      - production
      - staging

jobs:
  restrict-to-release-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge branch
        if: github.event.pull_request.base.ref == 'production' || github.event.pull_request.base.ref == 'staging'
        run: |
          if [[ ! ${{ github.event.pull_request.head.ref }} =~ release/.* ]]; then
            echo "Merges to main are only allowed from a release/ branch."
            exit 1
          fi 
