name: Test merging 

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Target environment for release
        options: 
        - staging
        - production

permissions:
  actions: write
  checks: write
  contents: write
  #deployments: write
  #id-token: write
  #issues: write
  #discussions: write
  #packages: write
  #pages: write
  pull-requests: write
  repository-projects: write
  #security-events: write
  #statuses: write

jobs:
  #check-source-branch:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: check source branch is release
  #      if: ${{ !startsWith(github.ref_name, 'release/') }} 
  #      uses: actions/github-script@v6
  #      with:
  #        script: |
  #          core.setFailed('You cannot release to ${{ inputs.environment }} from branch:${{ github.ref_name }}. Releases must come from a release branch!')
        
  merge_release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
  
      - name: Merging release
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: ${{inputs.environment}}
          message: Merge ${{ github.ref_name }} into ${{inputs.environment}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
